#!/bin/bash

RCM_EXPORT_IP=8080
RCM_EL="rcm-elasticsearch"
RCM_NET="rcm-network"

./deploy-myadmin

docker network create $RCM_NET
docker run -d --name=$RCM_EL --net=$RCM_NET elasticsearch

# Build web image
docker build --build-arg elasticsearch_ip=$RCM_EL -t rcm-web app/
docker run -d -p $RCM_EXPORT_IP:80 --name=rcm-web --net=$RCM_NET rcm-web

# Pull the rows from mysql db to elasticsearch
docker build --build-arg elasticsearch_ip=$RCM_EL -t rcm-pull scripts/
docker run --net=$RCM_NET --name=rcm-pull rcm-pull
