#!/bin/bash

npm install --no-bin-links --prefix app/server

RCM_EXPORT_PORT=8080
RCM_EL="rcm-elasticsearch"
RCM_NET="rcm-network"

docker network create $RCM_NET
docker run -p 9200:9200 -d --name=$RCM_EL --net=$RCM_NET elasticsearch

# Build web image
docker build --build-arg elasticsearch_ip=$RCM_EL -t rcm-web -f app/DevDockerfile app/
docker run -d -p $RCM_EXPORT_PORT:80 --name=rcm-web --net=$RCM_NET -v /$(pwd)/app:/opt/rcm rcm-web

# Pull the rows from mysql db to elasticsearch
docker build --build-arg elasticsearch_ip=$RCM_EL -t rcm-pull scripts/
docker run -a --net=$RCM_NET --name=rcm-pull rcm-pull
