#!/bin/bash
# The deploy file for java-backend

RCM_NET="rcm-network"

docker rm -f rcm-java
cp src/xml_fetch/* Docker/xml_fetch/
docker build -t rcm-java Docker/
docker run --net=$RCM_NET --link rcm-mysql:db --name rcm-java rcm-java

docker exec rcm-java /opt/rcm-java/start.sh
